# Generated by Django 6.0.1 on 2026-02-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='upadted_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
    ]
