# Generated by Django 6.0.1 on 2026-02-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eather', '0002_rename_upadted_at_employee_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='upadted_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='upadted_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
